#!/bin/bash
parent_dir=$(dirname $(pwd)); for file in *.html; do if [ ! -e "$parent_dir/$file" ]; then echo "$file meets conditions"; fi; if [ "$file" -nt "$parent_dir/$file" ]; then echo "$file meets conditions"; fi; done
